name: Rust CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build and create release
        run: |
          cargo build --release
          echo "Creating GitHub Release..."
          git tag $GITHUB_REF
          git push origin $GITHUB_REF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to push tags and create releases

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/release/fsi # Replace with your binary name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to create releases
